docker-compose.yaml

Introducing a healthcheck I've seen suggested (and successfully used in another project) to ensure that the PostgreSQL container is not only running, but also fully ready to accept incoming requests. Hoping this will solve the problem with occassionally failing tests on GitHub.

wait for PostgreSQL healthcheck before starting server

---

frontend/src/components/Playback/MatchingPairs.js
frontend/src/components/Playback/MatchingPairs.scss

This PR ensures the playing board is always centered on all devices.
It also fixes the nomatch animation bug where only one card would shake. This appeared when you clicked through the cards real fast, so that the nomatch class was still on a card from a previous turn and the animation didn't get triggered.

Feature er/tunetwins visual tweaks

---

frontend/src/components/PlayButton/PlayCard.js
frontend/src/components/Playback/Playback.js

This PR is a temporary solution to solve the latency with tunetwins when playing from Japan.
For every playcard an `<audio>` tag is created, with the same attributes as the main `<audio>` tag, but with an `id` labeled `buffer-<section.id>`.
These audio elements are never used, but preload the audio files in cache before the games begins.

Feature er/tunetwins external

---

.github/workflows/test.yml
README.md

Before, the `test` workflow would only run when pushing to `develop` or `main`, or on the `pull_request` trigger. Now, the `test` workflow will be triggered on a push to _any_ branch as per the varying preferences in the team.

Config: Configure test workflow to run on pushes to all branches

---

.env.dist
docker-compose.yaml
frontend/package.json
frontend/src/config/sentry.js
frontend/src/index.js
frontend/yarn.lock

This PR configures Sentry for the frontend (React) part of the application. This means that errors that occur in the browser will be send to Sentry automatically. Currently, I've configured it so that only 10% of the errors ocurring will be posted to Sentry to prevent us going over the limit. We can play with this percentage through time.
Browser errors that happen in both ACC and PROD will be sent to Sentry. In Sentry we can filter them based on their origin domain and many other factors.
I would like to share the credentials with you so you can also see the Sentry dashboard on Sentry.io, is there an official way to do it?
- Configure the Sentry DSN key obtained from @drikusroor in your `.env` file with the key `REACT_APP_SENTRY_DSN`
- Add the following route on top of your routes in …

Config: Configure Sentry for frontend

---

backend/experiment/models.py
backend/experiment/tests/test_model_functions.py

This PR fixes the incorrect plural naming of the _Experiment Series_ model, which is currently displayed as _Experiment Seriess_, but should be displayed as _Experiment Series_.
(For what it's worth)
Fixes #635

Fixed: Fix incorrect plural name of Experiment Series(s)

---

.github/workflows/ci.yml
.github/workflows/test.yml
backend/requirements/dev.txt
frontend/package.json

This PR adds linting jobs for both the frontend (`eslint`) and backend (`flake8`). The question right now is whether our linting settings/preferences are configured correctly and to our liking. Additionally, the linting job for the backend "fails", although I allowed it to fail. Maybe we can alter the `flake8` configuration so that it won't fail anymore, or we can allow it to fail and slowly fix all issues.

CI: Add linting jobs

---

backend/experiment/rules/eurovision_2020.py
backend/experiment/rules/kuiper_2020.py

Fix Eurovision2020 and Kuiper2020 expected_result in next_heard_before_action()

---

.github/workflows/storybook.yml

This PR makes sure Storybook is only deployed to Github Pages on the `develop` branch. We can change this later to `main` if we would like to, but I think it's interesting for people to see what we are working on before it's even on production.

CI: Enable publish storybook to github pages

---

backend/experiment/actions/playback.py
backend/experiment/actions/wrappers.py
backend/result/score.py
frontend/src/components/Playback/Autoplay.js
frontend/src/components/Playback/Playback.js
frontend/src/components/Trial/Trial.js
frontend/src/util/audioControl.js

Close #662. The current solution saves `decisionTime` in `window.sessionStorage` every time the player clicks a form during a `Trial`. For every playback view, we can now set whether we want to `resume_play` from where a previous player left off.
Will experiment with whether this could also be achieved with a useState hook at the `Experiment` level, but this approach works for the time being.

Fix problem with "sync" playback in SongSync

---

.github/workflows/ci.yml

The backend test job is currently failing on the `develop` branch because it tries to push a commit and push a generated code coverage badge to the `code-coverage-badges` branch. However, as the generated code coverage badge is identical to the existing one (code coverage percentage hasn't changed in the last commits and thus so hasn't the badge), it tries to commit "nothing". This causes git to throw an error, resulting in the step to fail.
This PR then fixes this in two ways:
- First, `continue-on-error: true` is set to `true` for this step, which means Github Actions won't see it as a failed step and thus as a failed job
- Second, a check is made as to whether the newly generated code coverage badge is different from the currently existing one. If it's identical, it will skip the …

Fixed: Failed backend test due to empty code coverage badge commit & push step issue

---

backend/aml/base_settings.py

This PR whitelists two CORS headers:
- `baggage`
- `sentry-trace`
Currently, the frontend adds these headers to requests towards the Django API for Sentry to be able to correlate errors in the frontend and backend. For example, something that might fail in the frontend might have something to do with something failing in the backend. As these events are now connected, Sentry can display the whole erroneous flow in its Dashboard, making it easier for us to debug.
See also: https://docs.sentry.io/platforms/javascript/usage/distributed-tracing/

Fixed: Sentry CORS issues

---

.github/workflows/teams-notifications.yml

This PR intends to configure notifications that will be pushed to the newly created experimental teams channel named [_Github activity (experimental)_](https://teams.microsoft.com/l/channel/19%3Ab803ff74120a4438ad6d937bfce24c64%40thread.tacv2/Github%20activity%20(experimental)?groupId=5c5b7168-27f0-450f-80a6-1a7e2635e09a&tenantId=) for certain events, such as:
- An issue gets assigned to someone
- A pull requests is assigned or closed or opened
- The tests pipeline fails
This is just an experiment for now. Please let me know if you think this is an overkill of notifications and we can cancel this little project again, or let me know which notifications you _are_ interested in receiving - there's [a whole bunch of events](https://docs.github.com/en/actions/using-workflows/events-that-trigge …

CI: Add Teams Notifications workflow

---

backend/README.md
scripts/compile-requirements

This PR documents how to add python dependencies to the Django backend. Instead of reading markdown, you might want to look at it here: https://github.com/Amsterdam-Music-Lab/MUSCLE/tree/docs/add-python-deps/backend#install-packages
* Does the added entry in `backend/README.md` accurately and correctly describe the process of adding and installing new Python dependencies?
* Should it be documented in `backend/README.md`, or perhaps in the `README.md` in the root of the repository or perhaps even in the [Wiki](https://github.com/Amsterdam-Music-Lab/MUSCLE/wiki)?
- I've moved the documentation to the wiki: https://github.com/Amsterdam-Music-Lab/MUSCLE/wiki/X.-Installing-python-packages
- I've added a script that automatically runs the two `pip-compile` commands

Docs: Add instructions for installing Python dependencies

---

backend/experiment/rules/musical_preferences.py
backend/experiment/rules/tests/test_musical_preferences.py

This branch adds a test to check that the information about the "most liked" songs presented to a participant in the musical preferences experiment are indeed those with the *lowest* score in the database. As tests should, this still showed some flaws in the logic, which - as far as the test can tell - are now fixed.

check correctness of get_preferred_songs function

---

frontend/package.json
frontend/src/components/Question/_ButtonArray.js
frontend/src/components/Question/_ButtonArray.test.js
frontend/src/scss/elements.scss
frontend/src/stories/Trial.stories.js
frontend/yarn.lock

This PR makes sure that whenever a button in a button group is "selected", this selection will be made clear visually to the user after navigating to the next form element. Like a checkbox, but then for a selected button.
Additionally, it adds the `checked` and `aria-checked` attributes to the buttons (which are in fact radio buttons) with the correct value.
Lastly, I've upgraded Storybook to a new version.
Resolves #656

Fixed: Show selected answer in button style

---

backend/experiment/rules/base.py
backend/experiment/rules/gold_msi.py
docker-compose.yaml
frontend/package.json
frontend/src/components/Experiment/Experiment.js
frontend/src/components/FloatingActionButton/FloatingActionButton.js
frontend/src/components/FloatingActionButton/FloatingActionButton.scss
frontend/src/components/FloatingActionButton/FloatingActionButton.test.js
frontend/src/components/UserFeedback/UserFeedback.js
frontend/src/components/UserFeedback/UserFeedback.scss
frontend/src/components/UserFeedback/UserFeedback.test.js
frontend/src/components/components.scss
frontend/src/scss/variables.scss
frontend/src/stories/Final.stories.js
frontend/src/stories/FloatingActionButton.stories.js
frontend/src/stories/UserFeedback.stories.js
frontend/yarn.lock

This pull request adds the FloatingActionButton and UserFeedback components to the project. It also includes various style updates and unit tests.
At the experiment's `feedback_info` you can supply a parameter to turn it on or off for a given experiment by setting `show_float_button` to `True`.
For example:
```py
def feedback_info(self):
info = super().feedback_info()
info['show_float_button'] = True
return info
```
It currently looks like this:
https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/8208970/1e199b58-207f-4740-b16b-77559a4b8435
- User sees floating feedback button in the center right on it and clicks it
- Floating Action Button opens with an animation
- User enters feedback in text input
- User clicks submit
- If successful, a "Thank you..." message is shown
- User can close …

Added: Add FloatingActionButton and UserFeedback components

---

.github/workflows/ci.yml
backend/.flake8
backend/requirements.in/dev.txt
backend/requirements/dev.txt
scripts/lint-back

This pull request adds Flake8 for linting the backend code. The `flake8` was already being run, but it turned out the `flake8` python wasn't even installed yet.
The flake8 linting job in the pipeline has now been configured to fail on linting errors. However, I've added a `.flake8` configuration to ignore all the issues we currently have. We can gradually un-ignore these issues (starting with the most important ones) and improve the quality of our codebase. My plan is to start with one of the issues that are rated as high priority in the `.flake8` file after this PR is merged.
The PR includes the following commits:
- chore(deps): Add Flake8 for linting
- config: Add .flake8 configuration file with flake8 rules
- ci: Update Lint Backend step to continue-on-error: false
- config: Add …

CI: Add Flake8 for linting

---

.github/workflows/ci.yml

This pull request removes an unnecessary condition in the CI workflow that caused the frontend coverage job to run for every commit in a PR.

Fixed(CI): Remove unnecessary condition in CI workflow

---

backend/experiment/actions/trial.py
backend/experiment/rules/listening_conditions.py
backend/experiment/rules/tests/test_listening_conditions.py
backend/result/utils.py

This pull request fixes the prepare_result function calls in listening_conditions.py by adding the missing key parameter. It also fixes the instantiation of the `Trial` class in the `next_round` method in the `listening_conditions` experiment. Furthermore, it adds type hints to the prepare_result function and the Trial class constructor. Additionally, it includes test cases for the ListeningConditions class.
Resolved #698

Fixed: Fix prepare_result function calls and add type hints

---

backend/experiment/rules/musical_preferences.py
backend/experiment/rules/tests/test_musical_preferences.py

This pull request fixes a bug in the `MusicalPreferences` class where an error was raised when retrieving preferred songs without a section. The bug was caused by a filter condition that included results without a section. This PR updates the filter condition to exclude results without a section, ensuring that the error is no longer raised.
Resolves #685

Hotfix(mpref): Fix preferred songs without section bug

---

backend/experiment/rules/musical_preferences.py
backend/experiment/rules/tests/test_musical_preferences.py

This PR is solely to keep `develop` up to date with the hotfix that had been merged to `main` earlier today.
* fix(muspref): Only fetch results with existing sections
* test(mpref): Add test case for preferred songs without section
* refactor: Remove unnecessary filters from the session's result set queries
* test: Don't create the sectionless results connected to the current session
(cherry picked from commit d502f9bd0994d9b2c4a756a2edaa298cf5a93a68)

Fix(mpref): Fix preferred songs without section bug (#708)

---

frontend/src/components/Question/_ButtonArray.js

React warns about passing the {checked} prop in the ButtonArray without a onChange method. This is rectified in this PR.

fix react warning about passing {checked} prop

---

frontend/src/components/Question/_ButtonArray.js

This pull request fixes a curly bracket issue in the ToggleButton component. The issue was caused by an extra closing curly bracket in the onChange event handlers. This PR removes the extra curly bracket to resolve the issue.
Related to #713

Fixed: Fix curly bracket issue

---

frontend/src/API.js

It turns out that there was still a call to `session.current` in the `API.finalizeSession` function. Not caught by a test, unfortunately. What would be a good way to catch these kind of problems? The `Final` component calls this function, but mocks it. Obviously, TypeScript would warn if the function is called with the wrong types of arguments, so perhaps we can indeed introduce it gradually.

fix: refer to session.id from finalizeSession

---

backend/section/admin.py
backend/section/forms.py
backend/section/models.py
backend/section/templates/change_form.html
backend/section/tests.py
backend/section/urls.py
backend/section/views.py

This pull request adds the ability to upload CSV files and export playlists to CSV and JSON formats in the PlaylistAdmin section.
Resolves #591

Added: Add upload and export functionality to PlaylistAdmin

---

backend/experiment/actions/trial.py
backend/experiment/rules/listening_conditions.py
backend/experiment/rules/tests/test_listening_conditions.py
backend/result/utils.py

* Fix: Fix prepare_result function calls in listening_conditions.py by adding key parameter
* fix: Fix Trial instantiation in ListeningConditions (second parameter is html, see trial.py)
* refactor: Add type hints to prepare_result function
* refactor: Include type hints to Trial class constructor
* Add test cases for ListeningConditions class
* fix(lint): Fix formatting in trial.py and remove unnecessary lines in test_listening_conditions.py
(cherry picked from commit 6f52358118ea5ae53b4a4789721d29e1c577490c)
Resolves #736

Hotfix: Fix prepare_result function calls and add type hints (#701)

---

backend/experiment/management/commands/createexperiment.py
backend/experiment/management/commands/templates/experiment.py
backend/experiment/management/commands/templates/test_experiment.py
backend/experiment/rules/__init__.py
scripts/manage

This PR adds a Django management command that allows a developer to create new experiments.
* It first asks the user for the experiment name
* Based on that name it will create a new file with the experiment name in snake case (e.g. `experiment/rules/snake_case.py`) based on a template in `experiment/management/commands/templates/experiment.py`
* It will register the experiment to `experiment/rules/__init__.py` (this might have to be removed later, see also #732 )
* Lastly, it will add a basic unit test in `experiment/rules/tests/test_snake_case.py`, based on the template in `experiment/management/commands/templates/test_experiment.py`
Additionally, this pull request adds a script that allows executing Django management commands through Docker, making it easier to execute this specific …

Added: Add a Django management command to create new experiments

---

backend/section/templates/change_form.html
frontend/src/components/Question/_ButtonArray.scss
frontend/src/stories/ButtonArray.stories.js

Previously, the button text ("___" in Categorization) was not hidden because the text was only hidden on disabled buttons. Now, it is hidden for enabled buttons as well. I suppose I thought it wasn't necessary before because I might have assumed the buttons were hidden before the playback was completed?
Resolves #741

Fixed(ButtonArray): Hide button text when .invisible-text is present, disabled or not

---

frontend/src/components/Histogram/Histogram.scss

This pull request removes the margin-bottom property in the Histogram.scss file which was causing unwanted spacing in the histogram component. 
Resolves #747

Fixed(MatchingPairs): Remove margin-bottom in Histogram.scss

---

backend/experiment/management/commands/templates/experiment.py

I was thinking along those lines for the template for `createexperiment`: add a `Trial` which demonstrates a typical setup. Still to be tested though, but just in general, @albertas-jn , do you think this could work? If you can already add documentation about the different methods in a typical rules file (i.e., first_round, next_round) to the wiki, that would certainly be helpful!
@drikusroor I removed the `feedback_info` method, since I figured we probably wouldn't *need* to override this - or is there a reason you did in the original template? I also got rid of the `questions` array in the `__init__`, because we can now select questions through the admin interface, and I'd rather that users choose that method over hard-coding them in the rules file.

add Trial to template

---

backend/experiment/forms.py
backend/experiment/models.py
backend/experiment/tests/test_admin_experiment.py

Resolves #670 (CSV export doesn't export the "question_key" of results)

Fixed: Fix export_table method to export question_key and add unit tests

---

frontend/src/components/App/App.js
frontend/src/components/Experiment/Experiment.js
frontend/src/components/Final/Final.js
frontend/src/components/Final/Final.test.js
frontend/src/components/Playback/MatchingPairs.js
frontend/src/components/Playback/MatchingPairs.test.js
frontend/src/components/StoreProfile/StoreProfile.js
frontend/src/stories/MatchingPairs.stories.js
frontend/src/util/__mocks__/stores.js
frontend/src/util/stores.js

This pull request refactors the existing stores to use Zustand's slice pattern.
Resolves #752

Refactor stores to use Zustand's slice pattern

---

backend/experiment/templates/edit-sections.html

This pull request fixes the input types for the start time and duration fields in the playlist editing section. The input types have been updated from type=text to type=number to ensure that only numeric values can be entered.
Resolves #765
@Evert-R I have assigned you as reviewer as I believe you made this feature
@chfin I have assigned you as well as it might help with confirming the fix was successful after it has been deployed to acceptance

Fixed: Fix input types for start time and duration fields in edit sections page

---

nginx/custom-nginx.conf

This pull request adds the `client_max_body_size` directive to the nginx configuration and sets it to `100mb`, allowing for larger file uploads.
@BeritJanssen did or do we have a file size limit configured already somewhere in Django?
Resolves #777

Fix: Increase file size limit for uploads in nginx configuration

---

backend/aml/base_settings.py

This pull request fixes the conditional initialization of Sentry based on the environment variable SENTRY_DSN. Previously, Sentry was always initialized regardless of whether the SENTRY_DSN variable was defined. With this fix, Sentry will only be initialized if the SENTRY_DSN variable is defined.
Resolves #769

Fixed(Sentry): Fix conditional initialization of Sentry based on environment variable SENTRY_DSN

---

docker-compose-deploy.yml

This pull request updates the port mapping in the docker-compose file for podman. The entrypoint for the nginx container is changed to always be 8080, similar to the AML Blog setup.

Config: Update port mapping in docker-compose file for podman

---

backend/experiment/management/commands/createruleset.py
backend/experiment/management/commands/templates/experiment.py
backend/experiment/management/commands/templates/test_experiment.py

This PR is a follow up of #766 after we have decided to rename the `createexperiment` command to `createruleset` to better reflect its purpose. See also [this comment](https://github.com/Amsterdam-Music-Lab/MUSCLE/pull/766#issuecomment-1953974269)
The templates are renamed accordingly as well.

Refactored(command) Rename createexperiment command to createruleset

---

backend/experiment/actions/base_action.py

This pull request refactors the BaseAction class to handle the case when the style parameter is missing. Previously, the class assumed that the style parameter would always be provided, which could lead to errors if it was not. With this change, the class now checks if the style parameter is None and handles it accordingly.
Related to #696

Fixed: Refactor BaseAction class to handle missing style parameter

---

.github/workflows/ci.yml

This pull request updates the code to only generate code coverage badges when pushing to the develop branch. This change ensures that code coverage badges are not generated unnecessarily (on main branch) and reduces conflicting coverage percentages. The code coverage badges will now always reflect the `develop` branch.

Chore: Only generate code coverage badges on push to develop

---

backend/experiment/management/commands/templates/test_experiment.py

This pull request refactors the import statement in the test_experiment.py file (aka the **ruleset unit test template**) from `from unittest import TestCase` to `from django.test import TestCase`. This change ensures that the correct TestCase class is imported and used for testing the Experiment model, and the `setupTestData` test method will be called automatically, just like in all other Django unit tests.
See also this similar problem: https://stackoverflow.com/questions/70835853/django-setuptestdata-doesnt-run

Fixed: Refactor import statement in test_experiment.py

---

docker-compose-deploy.yml

This pull request adds the `restart` option to the Docker services in the `docker-compose.yml` file. The `restart` option ensures that the services automatically restart if they fail or if the Docker daemon restarts. This improves the reliability and availability of the application as the new test & acc environment's containers are currently down after a github runner update.

CI: Add restart options to Docker services

---

.github/workflows/podman.yml

This pull request updates the Podman workflow to include the Sentry release action. It let's Sentry know of the release and the version and also uploads sourcemaps. This will improve the monitoring and error tracking capabilities of the application.
Resolves #755

CI: Update Podman workflow to include Sentry release action

---

.github/workflows/podman.yml

Prevent the podman workflow from always running (and thereby _deploying_ to ACC) on pull requests, which was still the case up to now.

Fixed(CI): Fix podman workflow on PRs

---

frontend/src/components/App/App.js

This pull request fixes the handling of the participant_id query parameter in the experiment URL. Previously, only the participant_id parameter was allowed, but now other query parameters are also allowed.
Resolves #838

Hotfix: Fix experiment URL participant_id query parameter handling

---

frontend/src/components/App/App.js

This pull request fixes the issue where the participantId was being passed even when it didn't exist. Now, the participantId is only passed as a query parameter if it exists in the URL.

Hotfix: Fix passing participantId only when it exists

---

backend/experiment/rules/matching_pairs_lite.py

Fix problem with section selection in `matching_pairs_lite`.

fix: select all sections which don't have tag 'Original'

---

backend/Dockerfile
backend/DockerfileDevelop

We just noticed that it may be problematic if the `apt-get update` call is cached separately from the library installs, as the install might try to pull an outdated version. This PR should fix that.

fix: move apt-get update to same layer as library installs

---

backend/experiment/admin.py
package.json

This import would cause the admin dashboard to throw an error, thereby making it impossible to update experiment series.

Fixed: Remove incorrect import

---

frontend/package.json
frontend/src/components/App/App.js
frontend/src/hooks/useDisableRightClickOnTouchDevices.js
frontend/src/hooks/useDisableRightClickOnTouchDevices.test.js
frontend/yarn.lock

This pull request adds the `@testing-library/react-hooks` dependency and includes a new hook called `useDisableRightClickOnTouchDevices`. The hook prevents the context menu from appearing on touch devices.
Resolves #857

Added: Add useDisableRightClickOnTouchDevices hook

---

backend/experiment/admin.py
backend/image/tests/test_admin.py

This pull request fixes the issue where the experiment name was not clickable in the admin dashboard. It adds a new method `experiment_link` to generate a link to the experiment's admin change page and updates the `ExperimentAdmin` class to display the experiment name as a clickable link.

Fixed: Fix experiment name link in admin dashboard

---

backend/section/admin.py

This pull request fixes a hard-coded redirect to the playlist overview page that caused problems when using a subpath like /server. The redirect has been updated to use the reverse function from Django's urls module.

Fixed: Fix hard-coded redirect to playlist overview

---

backend/experiment/rules/matching_pairs.py
backend/experiment/rules/matching_pairs_fixed.py
backend/experiment/rules/matching_pairs_lite.py

Address problem for Congo-MatchingPairs that the board used for the practice sessions should be fixed, but not too predictable.

fix: use random seed before shuffle

---

backend/experiment/rules/matching_pairs_lite.py
backend/experiment/rules/test_matching_pairs_fixed.py

This pull request fixes the deterministic randomisation method in the MatchingPairsFixed class. The random.shuffle() function is now called after combining the original and degraded sections, ensuring that the sections are shuffled correctly. Additionally, unit tests have been added to verify the correctness of the select_sections method.

Fixed: Fix deterministic randomisation

---

backend/experiment/actions/trial.py
backend/experiment/rules/congosamediff.py
frontend/src/components/PlayButton/PlayButton.jsx

This pull request fixes an issue where the section name, tag, or group could be missing in certain cases. It also adds typing for the FrontendStyle class and shows the experiment name in the app bar. Additionally, it refactors the PlayButton component to handle the disabled state and allow multiple playbacks if the argument `play_once = False` is present. Finally, it refactors the CongoSameDiff class to use the PlayButton component instead of Autoplay for playback while allowing playing the audio more than once.
- experiment name, section tag, group, name are not required anymore
- use play button instead of autoplay and allow multiple playbacks
- show experiment name in the top bar

Enhance(SameDiff): Handle undefined values, use play button with multiple plays allowed

---

.github/workflows/ci.yml
frontend/.pnp.cjs
frontend/package.json
frontend/vitest.config.ts
frontend/yarn.lock

This pull request fixes the coverage report generation and badge creation for the frontend. The changes include updating the coverage provider to 'v8' and the reporter to 'json-summary'. Additionally, the script for generating the coverage badge has been updated to use the correct coverage summary file.
Resolves #889

Fixed: Fix coverage report generation and badge creation for frontend

---

backend/experiment/rules/congosamediff.py
backend/experiment/rules/tests/test_congosamediff.py

This pull request adds validity checks for experiment sections in the CongoSameDiff class. It ensures that all sections have a group value and at least one section has the tag "practice". Additionally, it includes the following commits:
- feat: Include group in trial key to be able to distinguish them
- feat: Add validity checks for experiment sections in CongoSameDiff class
Resolves #901

Added: Save trial group as question key in results

---

.github/workflows/teams-notifications.yml

This pull request fixes an issue where special characters like double quotes were causing problems in Teams notification messages for issue and pull request titles. The fix involves escaping these special characters to ensure proper rendering of the titles in the notifications.

Fixed: Fix Teams notification messages to escape "special" characters in titles

---

backend/experiment/rules/congosamediff.py
backend/experiment/rules/tests/test_congosamediff.py

This PR adds the following things to the CongoSameDiff experiment rule set:
- Pick a random variant per trial based on the group number
- Improve validation logic, mention all errors when playlist is invalid instead of just the first one it encounters
It requires the playlist to have the following format:
- Name: Will be used for the `result_key`, so it can be whatever you think is convenient.
- Group: Will be used as the trial number from which a random variant will be picked. If you have 3 variants that you want to use as the first experiment trial, you should have three stimuli in group 1.
- Tag: Will be used to mark a trial as a practice trial.
| Name | Group  | Tag  | 
|---|---|---|
| Rhythm_Practice_Same  | 1  | practice  |
| Rhythm_Practice_Diff  | 2  | practice  |
| Rhythm_1_Same …

Added: Pick a random variant per trial for the CongoSameDiff Experiment

---

backend/experiment/admin.py
backend/experiment/templates/edit-sections.html
backend/experiment/tests/test_admin_experiment.py

This pull request fixes the word-wrap issue in the edit-sections.html file that would make the filename disappear behind the next column if it was too long. The word-wrap property is added to the .form-filename class to ensure that long filenames are properly displayed.
Additionally, this PR slightly refactors the admin overview of Experiment and ExperimentSeries by:
- Improving the column names, and by 
- Adding links to the actual experiment and experiment collection in the slug column that are opened in a new tab. Just a simple quality of life improvement that saves you the time and effort to retype the whole url/slug of the experiment when you want to test/use it. Based on whether we are in DEBUG mode, it prefixes the url with `http://localhost:3000`. On TST/ACC/APP this prefix won't …

Fixed: Fix word-wrap issue in edit-sections.html and add links to experiment and collection in admin overview

---

backend/experiment/serializers.py
backend/experiment/views.py
frontend/src/components/ExperimentCollection/ExperimentCollection.scss
frontend/src/components/ExperimentCollection/ExperimentCollectionDashboard/ExperimentCollectionDashboard.test.tsx
frontend/src/components/ExperimentCollection/ExperimentCollectionDashboard/ExperimentCollectionDashboard.tsx
frontend/src/types/Experiment.ts

Fix routing issue by using Switch instead of BrowserRouter in ExperimentCollection.tsx
Add started_session_count property to Experiment interface in Experiment.ts
Update Experiment interface in Experiment.ts to remove optional session count properties
Update ExperimentCollectionDashboard to display started and finished session counts in Experiment links
Update tests for newly added started session counter badge
Resolves #912

Added: Show started session count in experiment collection tiles

---

backend/experiment/templates/edit-sections.html

This PR resolves the bug that the displayed order of the group and tag inputs didn't match the order of the csv input order. 
resolves #942

reverse order of group/tag input fields to match csv input

---

backend/experiment/rules/congosamediff.py
backend/experiment/rules/tests/test_congosamediff.py

This pull request adds the implementation of a factorial design based on groups with numbers and variants with uppercase letters, in which the chosen pattern of groups & variants is will be based on the participant id url.
Let's say an experiment has 2 trials (I shall refere to these as groups) in which every group has a two variants (A & B), the CSV would look like this (ignoring the practice rounds):
| Name (name column) | Group (group column) | Variant (tag column) |
|---|---|---|
| Rhythm 1 Same | 1 | A |
| Rhythm 1 Diff | 1 | B |
| Rhythm 2 Same | 2 | A |
| Rhythm 2 Same | 2 | B |
The idea is to rotate the possible combinations of groups and variants over the participants. In this scenarios, we would have 4 different patterns:
1. 1A & 2A
2. 1A & 2B
3. 1B & 2A
4. 1B & 2B
Participant 1 …

Added: Implement factorial design based on groups with numbers and variants with uppercase letters

---

backend/experiment/rules/congosamediff.py

This pull request adds a "Return to Dashboard" button to the SameDiff experiments, similar to the existing button in the matching pairs test. The button will bring the user back to the Dashboard of the same participant, allowing for starting a new experiment from there.
Resolves  #935

Added: Add back to dashboard button to SameDiff experiments

---

backend/experiment/rules/congosamediff.py
backend/experiment/rules/tests/test_congosamediff.py

In a musicality battery experiment with 2 trial groups and 2 variants per trial group, participants should now get the following group-variant combinations (patterns):
1. AB
2. BA
3. AB
4. BA
For 2 groups with 3 variants:
1. AB
2. BC
3. CA
4. AC
5. CB
6. BA
For 4 groups with 3 variants:
1. ABCA
2. BCAB
3. CABC
4. ACBA
5. BACB
6. CBAC

Added: Add rotating patterns to musicality battery experiment

---

frontend/src/components/Playback/Playback.jsx
frontend/src/components/Preload/Preload.jsx

> This pull request fixes the "unknown view" error by adding the VISUALMATCHINGPAIRS experiment type to the Playback component.
The visual matching pairs rules set still returned the view as `VISUALMATCHINGPAIRS`, causing an "unknown view" error. Either we do it like this (by keeping the rule set and adding the view to `Playback.jsx`) or we remove this rules set and go full monty on the matching pairs rules sets and use the `determine_play_method`, which is more automagically but might also give the user less control (what if the user uses an audio format that's not in the list?).
> It also refactors the fetch requests by removing the 'no-cors' mode.
As for the CORS errors, I'm not getting them 😅 Have you also experienced them on ACC or APP? Maybe we can compare our `.env` files. In the …

Fixed: Fix "unknown view" error and refactor fetch requests

---

backend/aml/production_settings.py
backend/experiment/rules/base.py
backend/experiment/rules/tests/test_base.py

Update the RELOAD_PARTICIPANT_TARGET URL in the production settings to remove the trailing slash. This ensures consistency in the URL format.
- refactor: Make string formatting of social media share link url more readable
- Refactor the string formatting of the social media share link URL to improve readability. This change does not affect the functionality of the code.
- test: Add test for social media info in BaseTest
Resolves #950

Fixed: Update RELOAD_PARTICIPANT_TARGET URL in production settings to avoid double slashes in social media share url

---

frontend/src/components/MatchingPairs/MatchingPairs.jsx

The first card is now set to seen on the first move of a turn.
- Score will now be `misremembered` when a first card with status `seen`  is used as the second card in a future turn.
- When 2 cards with a status `seen` are a match the score is `Good Job`. This was already the case, but didn't work properly because the first card in a turn was never set to `seen`  
Fixes #949

Set first card status to seen

---

backend/experiment/rules/congosamediff.py

The `artist` field of  `section.song` is now used for the `expected_resonse` field in the results. 
This doesn't do anything to the logic, but  makes it easier to overview the results in the admin interface and in the json data export. 
resolves #936

set artist field as expected_response in the results

---

backend/experiment/rules/thats_my_song.py

A fix for the problem we just noticed with That's My Song: it won't continue after the first explainer. Caused by an orphan `Playlist` view.

fix: delete playlist action from first_round

---

frontend/src/components/MatchingPairs/MatchingPairs.jsx

reset response interval for first card, in case the card already has a value from a previous turn

reset response interval

---

backend/experiment/templates/widgets/markdown_preview_text_input.html

This pull request refactors the MarkdownPreview widget to allow for multiple instances on a single page. Previously, it would only look for one instance, causing both markdown preview widgets to break as they were conflicting.
Resolves #990

Fixed: Refactor MarkdownPreview widget to support multiple instances

---

backend/experiment/rules/congosamediff.py

The participant_id assignment in the CongoSameDiff class has been updated to use the session's participant ID instead of using the participant_id_url property as a base for the pattern index.
Resolves #1001

Added: Update participant_id assignment in CongoSameDiff class

---

frontend/src/components/Preload/Preload.jsx

This PR fixes #1006 
The `webAudio.clearBuffers()` function was moved in #1003  to act as the cleanup function for the react hook it's in.
When preloading a section that was also used in the previous turn, the preloading of the section was skipped by `webAudio.checkSectionLoaded()` after which the buffers were cleared on cleanup and there was nothing to play, which caused the experiment to freeze.
Putting the `webAudio.clearBuffers()` back in place solved the problem.
As most experiments only use 1 section per round the `webAudio.clearBuffers()` was meant to prevent the loaded buffers from taking up to much memory:  Otherwise if there were 30 rounds with unique sections, all 30 buffers would remain in memory untill the experiment was finished, which could cause problems.
I made some …

Clear buffers before preloading first section

---

frontend/src/util/webAudio.js

Resolves #1012
This PR eliminates the double `/server/server` prefix that was caused by both the frontend and the backend adding a `/server` path to the urls that fetches the sections.
In this solution, I have removed it from the frontend part as the section url received from the backend already contains the `/server` path configured through the `AML_SUBPATH` environment variable. The backend uses a reverse url function that automatically adds that path already. See also here: https://github.com/Amsterdam-Music-Lab/MUSCLE/blob/3c0382b70b63742d7f0d0f75d8e64383f3bd01ff/backend/section/models.py#L291-L293

Fixed: Fix fetch URL in loadBuffer function by not prefixing the url with MEDIA_ROOT

---

.github/workflows/podman.yml
frontend/src/util/webAudio.js

This PR adds several missing / incorrectly defined environment variables to the frontend build & deploy workflow and compose file and thereby fixes the deploy process.
Additionally, the rules for deployment have been altered to make it easier to manually deploy a branch:
- If you manually trigger the workflow for the `main` branch, it will deploy the current `main` branch to the Acceptance environment.
- If you manually trigger `any` other branch, it will deploy that branch to the Test environment.
Related to and cherrypicked from #1007 in order not to pollute the `main` branch with features not ready to be released yet.

Fix (CI): Fix frontend deployment

---

.github/workflows/podman.yml

This newly added GitHub actions workflow job is configured to deploy whenever a new tag is created. This is different from the job that deploys to Acceptance, which also deploys on commits to `main`.
Related to #1014

CI: Configure deployment to Production server

---

backend/experiment/rules/thats_my_song.py

#1021 introduced a different ordering of the `hooked` rules file's `first_round` array. This meant that "That's My Song" picked the wrong action from it.

fix: return correct content for first_round

---

.github/workflows/podman.yml

The workflow and individual job seemed to have conflicting conditions:
- The workflow was configured to run after a release creation
- The deploy to production job was configured to run on a commit with a tag
Now, the workflow and the deploy to production job should run on _both_ a release creation as well as a tag creation. Additionally, one can do a manual workflow trigger on a tag to deploy to production.

Fixed: Deploy to production on tags and release creation

---

backend/experiment/forms.py

This pull request fixes the return value in the `clean_playlists` method of the experiment form. Previously, if there were no playlists, the method would return `None`, but now it correctly returns the cleaned data. This ensures that the form validation works as expected.

Fix return value in the experiment form's clean_playlists method

---

backend/experiment/forms.py
backend/experiment/rules/base.py
backend/section/forms.py
backend/section/models.py
backend/section/validators.py

This pull request fixes the file existence validation in the Playlist model and admin form. 
The `clean_csv` method in the Playlist model now performs file existence validation for section files. It checks if the referenced files exist using the `file_exists_validator` function. If any file is not found, a `ValidationError` is raised and added to the `csv` field errors.
Additionally, it fixes an existing problem in the experiment rules validation method.

Added: Validate file existence validation in Experiment & Playlist forms

---

backend/experiment/models.py
backend/experiment/tests/test_views.py
backend/experiment/views.py

This pull request fixes the serialization of the theme in the `get_experiment` view. Previously, the theme was not being serialized correctly, resulting in an internal server error. This PR updates the serialization logic to correctly serialize the theme.
Additionally, extra tests are added to test the serialization of get_experiment and get_experiment_collection.
PS. @BeritJanssen  I noted that we don't use `serialize_experiment` in the `get_experiment` view method. Is that on purpose? Because the `get_experiment_collection` view method does seem to use `serialize_experiment_collection`. 🤔
Resolves #1049

Fixed: Fix theme serialization in get_experiment view

---

backend/experiment/rules/base.py
backend/experiment/rules/hooked.py
backend/experiment/rules/matching_pairs.py
backend/experiment/rules/tests/test_base.py
backend/experiment/rules/thats_my_song.py
backend/experiment/rules/visual_matching_pairs.py
frontend/src/components/Experiment/Experiment.jsx
frontend/src/components/Final/Final.jsx
frontend/src/components/Final/Final.test.jsx
frontend/src/components/Final/FinalButton.tsx
frontend/src/stories/Final.stories.jsx

This pull request fixes the rendering of the "Play again" button URL in the Final component. Previously, the backend would send an absolute url (inc. domain) to the frontend, which is incompatible with React Router's Link component, which expects a relative path.
First, the backend now only sends relative paths for the Play again button link in the That's my song & Hooked experiment rules.
Second, the frontend checks whether the received button link from the Final action is relative or absolute (whether it is prefixed with "/") and renders a Link or anchor tag (<a>) component/element accordingly.
Resolves #1046

Fixed: Fix play again URL rendering

---

frontend/src/components/App/App.tsx
frontend/src/components/Final/Final.test.jsx
frontend/src/components/Final/FinalButton.tsx
frontend/src/components/InternalRedirect/InternalRedirect.tsx
frontend/src/config.ts

Fix internal Final button link, which wouldn't cause an experiment to reload as the user was already on that page, by introducing an InternalRedirect.
The InternalRedirect has its own route and then redirects the user to the correct page with the correct search params. In short, it will lead you from `/thats_my_song?participant_id=123` to `/redirect/hats_my_song?participant_id=123`, which in turn will lead you back to `/thats_my_song?participant_id=123`, which will then trigger an experiment reload.
Alternatively, we could also just revert back to the earlier used anchor tag (<a>), which will do a full page reload but causes a little screen flash / glitch to appear as it reloads all the HTML / JS & CSS and shows an empty page for some milliseconds.
There was an earlier attempt #1051  to …

Fixed: Fix internal Final button link (v2)

---

backend/experiment/rules/base.py
backend/experiment/rules/hooked.py
backend/experiment/rules/huang_2022.py
backend/experiment/rules/tele_tunes.py
backend/experiment/rules/thats_my_song.py
backend/question/demographics.py
backend/question/utils.py

After merging, as discussed on another channel, I ran into problems due to a missing import in the Teletunes questions, which in turn, revealed a problem with a circular import, which I propose to fix by removing the defaults for the `questions=` argument in `question_by_key` and `total_unanswered_questions` of `question.utils`.

Fix: Teletunes questions import and circular import

---

backend/experiment/rules/toontjehoger_5_tempo.py

Added: Add playlist group validation to ToontjeHoger5Tempo rule

---

.github/workflows/podman.yml

This PR properly stops the running containers before deployment using `podman-compose down` before deploying the containers using `podman-compose up` in both ACC & PROD. Additionally, I've moved the `podman-compose down` command for the TST environment to run *after* the build step to minimze downtime.

Refactor deployment process to properly stop containers before deployment

---

backend/aml/base_settings.py
backend/experiment/tests/test_views.py
backend/experiment/views.py
backend/image/serializers.py
backend/theme/serializers.py
backend/theme/tests/test_serializers.py
frontend/src/components/Experiment/Experiment.jsx
frontend/src/components/ExperimentCollection/ExperimentCollectionDashboard/ExperimentCollectionDashboard.tsx
frontend/src/components/Footer/Footer.tsx

This branch fixes a problem on the servers, in which image requests are incorrectly prefixed with `API_ROOT`. Instead, this branch prefixes the `BASE_URL` for the backend image serialization.

fix: include `BASE_URL` in image file serialization

---

backend/experiment/actions/playback.py
backend/experiment/rules/toontjehoger_2_preverbal.py
frontend/src/components/Playback/Multiplayer.scss
frontend/src/components/Playback/Playback.jsx
frontend/src/scss/color-schemes.scss

I noticed that the "Preverbal" experiment, which uses the "ImagePlayer", still had unstyled play and response buttons. I added an extra colour category for `neutral` and `neutral-inverted`, which styles the last element in an array to teal in both cases.
I also fixed a bug: the preverbal rules file still passed a `label_style` argument (which was originally picked up by the frontend), instead of `labels`.

fix: TH Preverbal styles and player labels

---

backend/experiment/serializers.py
frontend/src/components/ExperimentCollection/ExperimentCollectionDashboard/ExperimentCollectionDashboard.test.tsx
frontend/src/components/ExperimentCollection/ExperimentCollectionDashboard/ExperimentCollectionDashboard.tsx
frontend/src/components/Header/Header.tsx
frontend/src/components/Logo/Logo.tsx
frontend/src/types/Theme.ts

This pull request includes the following changes:
- Removed unused code in the header component.
- Formatted the Logo component.
- Convert markdown to html in the get experiment collection endpoint serializer.
- Added the ability to show the experiment collection title and as formatted html.
Resolves #1100

Added: Show experiment collection title & description

---

.github/workflows/podman.yml

The e2e job for running the e2e tests would already start before the deployment to acceptance was done, i.e. in parallel. This extra configuration parameter ensures that the e2e tests will be run *after* the deployment to acceptance has been completed.

Fixed(CI): Add needs dependency for acceptance deployment in podman workflow

---

backend/experiment/rules/toontjehogerkids_5_tempo.py
backend/session/models.py

See also this comment: https://github.com/Amsterdam-Music-Lab/MUSCLE/issues/1106#issuecomment-2163369748
This seems to fix the problems in TH5 Kids - Tempo experiment as discussed in #1106, but I'm not completely sure what effect it might have on many other experiments. Maybe other experiments *do* want to pick a random section from the same song? It almost seems like it's the whole point of this method...
Maybe we need something like a `get_specific_section_from_song` method; in which the filter is leading and not a random pick?
Related to #1106

Fixed: Also apply filter_by filter on section filter in `section_from_any_song` session model method

---

backend/experiment/tests/test_views.py
backend/image/serializers.py
backend/theme/serializers.py
backend/theme/tests/test_serializers.py
frontend/src/components/ExperimentCollection/ExperimentCollection.test.tsx
frontend/src/components/ExperimentCollection/ExperimentCollectionDashboard/ExperimentCollectionDashboard.test.tsx
frontend/src/components/Logo/Logo.tsx
frontend/src/types/Image.ts
frontend/src/types/Theme.ts

Previously, the logo in the theme configuration was only serialized as a URL. This pull request updates the serialization to include the complete logo object, including the title, description, file, alt, href, rel, and target attributes. Additionally, it enables the href feature on logo click, allowing users to navigate to a specified URL when clicking on the logo.
Resolves #1115

Added: Serialize complete logo instead of just logo url and enable href feature on logo click

---

backend/experiment/templates/widgets/markdown_preview_text_input.html

Instead of a hard-coded `/experiment/render_markdown` url, it now uses the reverse url feature which is less error prone and automatically adds the SUBPATH if present.
Resolves #1119

Fixed: Update fetch URL in markdown_preview_text_input.html

---

.github/workflows/db-backup-template.yml
.github/workflows/podman.yml

This PR does two things:
* It executes a backup job before it deploys to the acceptance or the production environment. The backup job needs to be successful before the deployment jobs can even start.
* It adds a timestamp to the backup filenames as well, since there might be more than once backup per day now, depending on the amount of deployments we do.

CI: Backup before deployment to ACC & PROD

---

frontend/src/components/ExperimentCollection/ExperimentCollection.tsx

This will probably fix several Sentry errors related to missing properties on the experiment collection (which is null) when it is not found.
And of course it's a better message to show to users. :-)

Added: Add error message for missing experiment collection

---

backend/experiment/templates/collection-dashboard-sessions.html

This PR replaces a missing ```participant_url_id``` with the participant.id, and a missing ```finished_at``` for "-" in the sessions table

show alternative for None in session table (url_id and finished_at)

---

backend/experiment/rules/speech2song.py
backend/experiment/rules/util/practice.py
backend/requirements.in/base.txt
backend/requirements/dev.txt
backend/requirements/prod.txt

The commit removes the `IPToCC` package from the base requirements file. This package was used to get the country code from an IP address, but it is no longer needed and caused 15m Docker image build times due to its dependency on the `pandas` library, which had to be rebuilt every time.
Additionally, it also removes `numpy` as a dependency as there were only 4 lines of code in 2 files that were using it and which were very easy to replace with the already built-in python library of `random`. NB: you can't see `numpy` removed from `base.txt` as it was a dependency of `IPToCC` too.

Chore(deps): Remove IPToCC and numpy from base requirements

---

backend/experiment/static/block_admin.js
backend/experiment/templates/collection-dashboard-sessions.html

This pull request includes changes to update the URL matching and references to "Experiment" to use "Block" instead. The `block_admin.js` file has been updated to use "block" in the URL matching, and references to "Experiment" have been changed to "Block" in the HTML template.
See also https://github.com/Amsterdam-Music-Lab/MUSCLE/pull/1169#issuecomment-2217424810

Refactor: Refactor URL matching and references to Experiment to use Block

---

frontend/src/API.ts
frontend/src/components/Profile/Profile.tsx
frontend/src/stories/ProfileView.stories.jsx

The Profile component is currently written in JavaScript and this pull request converts it to TypeScript. This will improve type safety and make the codebase more maintainable.
Fix "points" string variable in Profile component (see screenshot below) as it tried to get the "points" string from data directly instead of from `data.messages`

Refactor: Refactor Profile component to TypeScript

---

backend/experiment/serializers.py
backend/experiment/tests/test_views.py

Fixed: Add improved check for social_media_config existence and add test

---

.gitignore
backend/experiment/rules/tests/test_beat_alignment.py
backend/experiment/rules/toontjehoger_1_mozart.py
backend/experiment/tests/test_views.py
backend/experiment/views.py
backend/image/tests/test_admin.py
backend/participant/tests.py
backend/participant/utils.py
backend/session/models.py
frontend/src/API.ts
frontend/src/components/Block/Block.tsx
frontend/src/components/Trial/Trial.tsx
frontend/src/types/Block.ts

This pull request includes a refactoring of the `get_block` function to phase out the `first_round` methods and create a session directly in the `get_block` function. If the `first_round` does not exist anymore in a block's rules file, it will call `next_round` directly. The frontend has also been updated to take the session_id from the get_block response. `get_block` will still call `first_round` if it does exist on the block's rules file in question. This allows us to phase it out over time and prevent this PR from becoming a monster to review.
Additionally, tests have been fixed and added after the refactoring of the `first_round` methods and session creation in `get_block`.
Finally, the `Block` and `Trial` component have been partially configured to TypeScript and some types have been …

Refactor: Start phasing out `first_round` and create session in `get_block`

---

backend/participant/admin.py

Fix block filter where it still tried to filter on a session's experiment, which we now call "block".

Fixed: Fix block filter in ParticipantAdmin

---

frontend/src/components/App/App.tsx
frontend/src/components/InternalRedirect/InternalRedirect.test.tsx
frontend/src/components/InternalRedirect/InternalRedirect.tsx
frontend/src/config.ts

This pull request fixes the `InternalRedirect` component by updating the import statements and refactoring the component to use the `useParams` and `useLocation` hooks instead of the `RouteComponentProps`.
Resolves #1212

Fixed: Fix InternalRedirect component

---

.github/workflows/ci-backend.yml
.github/workflows/ci-frontend.yml
.github/workflows/storybook.yml

This pull request updates the GitHub Actions checkout action from v3 to v4. The updated action is used in the backend and frontend test and lint jobs. This update ensures that the latest version of the checkout action is being used, which may include bug fixes or new features.

CI: Update GitHub Actions checkout action to v4

---

backend/participant/models.py
backend/participant/tests.py

Allows to sum participant profile scores based on QuestionGroup key.
Closes #135

Add participant score_sum()

---

backend/experiment/actions/form.py

I discovered this while testing the Speech2Song experiment: `TextQuestion` types wouldn't display anymore, since the default value for `max_length` is `None` instead of a number. This teensy PR fixes that.

fix: missing max_length of TextQuestion

---

frontend/src/components/Block/Block.test.tsx
frontend/src/components/FeedbackForm/FeedbackForm.tsx
frontend/src/components/HTML/HTML.test.tsx
frontend/src/components/HTML/HTML.tsx
frontend/src/components/Histogram/Histogram.test.tsx
frontend/src/components/Histogram/Histogram.tsx
frontend/src/components/MatchingPairs/MatchingPairs.tsx
frontend/src/components/MatchingPairs/PlayCard.test.jsx
frontend/src/components/MatchingPairs/PlayCard.test.tsx
frontend/src/components/MatchingPairs/PlayCard.tsx
frontend/src/components/PlayButton/PlayerSmall.jsx
frontend/src/components/Playback/ImagePlayer.test.tsx
frontend/src/components/Playback/ImagePlayer.tsx
frontend/src/components/Playback/MultiPlayer.test.tsx
frontend/src/components/Playback/MultiPlayer.tsx
frontend/src/components/Playback/Playback.test.jsx
frontend/src/components/Playback/Playback.test.tsx
frontend/src/components/Playback/Playback.tsx
frontend/src/components/Preload/Preload.tsx
frontend/src/components/Reload/Reload.test.tsx
frontend/src/components/Reload/Reload.tsx
frontend/src/components/Score/Score.test.jsx
frontend/src/components/Trial/Trial.tsx
frontend/src/hooks/useResultHandler.ts
frontend/src/types/Playback.ts
frontend/src/types/Section.ts
frontend/src/types/Trial.ts
frontend/src/util/audio.ts
frontend/src/util/webAudio.ts

This pull request includes several commits that refactor and convert components to TypeScript, fix linting errors, and improve typing. The commits also include adding unit tests for the Reload component, adding interfaces for trial configuration settings, and defining playback types and interfaces.

Refactor and convert components to TypeScript, fix linting errors, and improve typing

---

frontend/src/components/Block/Block.tsx
frontend/src/components/Final/Final.tsx
frontend/src/components/Playback/Playback.tsx
frontend/src/components/Trial/Trial.tsx
frontend/src/types/Block.ts

Resolves 🐛 [BUG] - Warning: A props object containing a "key" prop is being spread into JSX in `Block.tsx` #1221
Propose removing unused data argument from setView function in Playback.tsx
Do we even need to pass a `key` to the children components? Perhaps we can simplify it and remove it.

Fixed: Fix warning about key in spread props and make key explicit

---

frontend/src/components/Block/Block.tsx

- Add 'key' property to BlockState interface
- Implement key increment in updateState function
- Ensure child components re-render on state changes
This change addresses an issue where child components weren't
re-rendering properly when the state was updated multiple times
with similar data.

feat(Block): Add key prop to force child component re-renders

---

frontend/src/components/Block/Block.tsx

Fixing above bug (without issue). Close #1221. This solution reverts to setting the key with `Math.random`, and setting it explicitly on child views of the `Block` component. Additionally wraps the key in its own `setState`. Alternatively, we could just do `<Trial key={Math.random()} {...attrs}/>` and so forth, but I thought this was slightly less wordy. Also renamed `BlockState` to `ActionProps`, perhaps we can rename `state` to `action` when we properly type these props. That's going to make things much clearer IMO.

Bugfix: rerender consecutive views of same type

---

backend/experiment/static/experiment_form.css
backend/experiment/static/experiment_form.js

We can also look into integrating this little feature into *all* forms automatically, but I think right now only the experiment form can grow big enough to actually need this feature, right?
Resolves #1226

Added: Make submit row fixed on the bottom of the screen until the user scrolls down completely

---

frontend/src/components/Block/Block.tsx
frontend/src/util/stores.ts

Fixes 🐛 [BUG] - `next_round` gets called twice on initialization #1261
This pull request fixes the issue where the `next_round` endpoint is called twice on initialization. As the `theme` was set using `setTheme` in the same `useEffect`, it re-triggered this same `useEffect` before the initial `continueToNextRound` was resolved, thereby calling the `continueToNextRound` function a second time.

Fixed: Fix duplicate `next_round` call by handling theme logic in a separate effect

---

.github/workflows/docs.yml
frontend/.storybook/main.js

This pull request refactors the workflow file to build and publish both the documentation and Storybook simultaneously.
Instead of directly artifacting and deploying the `frontend/storybook-static` directory, the workflow is now configured to create and use the `docs-pages` directory in the root of the repository which gets published to Github Pages. Storybook is then configured to publish its build into `docs-pages/storybook` and update its internal links (`config.base`) to be prefixed with `/MUSCLE/storybook/` (`MUSCLE` is this repository's Github Pages' path, `storybook` is the subdirectory of storybook)
I've created a dummy `index.html` with a link to the Storybook site that shows that it works: https://amsterdam-music-lab.github.io/MUSCLE. This should probably removed when the …

CI: Refactor workflow file to build and publish Documentation website and Storybook simultaneously

---

frontend/src/components/Circle/Circle.scss

Resolves #1271
This worked in my local storybook, let's first see if it transfers to staging too

Fixed (style): Prevent percentage circle from overlapping background circle

---

frontend/src/components/Question/_ButtonArray.scss

This branch sets different column gaps between buttons in an array, based on the number of buttons, and the viewport width.

Fix button array spacing

---

frontend/src/components/App/App.tsx
frontend/src/hooks/useDisableIOSPinchZoomOnTouchDevices.test.ts
frontend/src/hooks/useDisableIOSPinchZoomOnTouchDevices.ts
frontend/src/scss/layout.scss

This pull request adds a new hook called useDisableIOSPinchZoomOnTouchDevices to the frontend codebase. The hook is responsible for preventing pinch zoom gestures on iOS devices. It is used in the App component to disable pinch zoom on touch devices. Additionally, the pull request includes necessary file changes to implement the hook and add the touch-action property to disable pinch zoom on iOS.
Additionally, the css-property `touch-action: manipulation;` is added to the body root class in order to prevent touch actions.
Resolves #1274

Added: Disable pinch zoom on iOS

---

frontend/src/components/Circle/Circle.scss
frontend/src/stories/Circle.stories.jsx

* 1. is on Firefox, 2. is on Safari
Resolves #1271

Fixed(style): Move percentage circle down 100% to align with background circle

---

frontend/vitest.config.ts

Previously, a bunch of files such as stories, yarn-related, storybook-static-related files would also be taken into account to calculate the code coverages percentages. It therefore resulted into a lower percentage than the "actual" code coverage percentage.
Additionally, I updated the vitest configuration file to also output code coverage line information in the terminal (next to the already existent json file)

CI(coverage): Exclude a whole bunch of unneeded directories and files used to calculate the frontend code coverage percentages

---

backend/experiment/rules/toontjehoger_1_mozart.py
backend/experiment/rules/toontjehoger_2_preverbal.py
package.json

This branch fixes the following issues:
- on Safari, some images would be squashed on narrow viewports. This was caused by the height setting, I removed it. I'm not sure what the intention was behind it, but after the fix I don't see any problems on Safari or Chrome with different viewports.
- the name & composer of sections used in the Toontjehoger Mozart Effect are very long (they include not only the name of the composer, but also of the ensemble and conductor), so I removed the formatting with non-breaking-spaces to address this problem:
Again, I couldn't see obvious drawbacks of allowing the interface to break between words in the section's name / artist description.

ToontjeHoger Kids hotfix

---

frontend/src/components/AppBar/AppBar.jsx
frontend/src/components/AppBar/AppBar.test.jsx
frontend/src/components/Experiment/Experiment.jsx
frontend/src/components/ExperimentCollection/ExperimentCollectionDashboard/ExperimentCollectionDashboard.tsx
frontend/src/components/Logo/Logo.tsx
frontend/src/components/Page/DefaultPage.jsx
frontend/src/components/Page/DefaultPage.test.jsx
package.json

~Resolves #1301~ Resolves #1296
I seem to remember having overheard this issue was discovered on production and would ideally be fixed before Thursday (2024-10-03), hence the PR to `main` as a hotfix.

Refactor: Remove `logoClickConfirm` and make user go to the experiment dashboard directly

---

backend/experiment/rules/categorization.py

This PR fixes an inconsistent fix for removing the `first_round` method, as well as a problem with too generous find & replace after renaming `session.rounds_passed` to `session.get_rounds_passed`.

Fix #1308: adjust categorization rules file

---

frontend/src/components/FeedbackForm/FeedbackForm.tsx
frontend/src/components/Trial/Trial.test.tsx
frontend/src/components/Trial/Trial.tsx

This PR addresses #1310. The FeedbackForm now calls `makeResult` instead of `onResult` and `onNext` directly.

Fix Hooked experiment flow

---

backend/section/views.py

I noticed a problem that seems to have gone unnoticed so far: in development, if you have filenames starting with a `/`, the `os.path.join` method will ignore anything before the filename, as it considers it to be an absolute path. In that case, it will try to fetch `/filename.mp3`, instead of `/upload/filename.mp3`.

Fix section retrieval during development

---

backend/experiment/rules/rhythm_discrimination.py
backend/experiment/rules/tests/test_rhythm_discrimination.py

Additional to fixing the title issues, I've added tests that validates the titles of the rounds, along with the rest of the block flow.
Related to #1325

Fix: adjust trial title logic for rhythm discrimination rounds

---

frontend/src/components/App/App.tsx
frontend/src/components/Cup/Cup.scss
frontend/src/components/Profile/Profile.scss
frontend/src/components/Profile/Profile.tsx
frontend/src/components/Profile/ProfileView.tsx
frontend/src/components/Rank/Rank.scss
frontend/src/components/Rank/Rank.tsx
frontend/src/stories/ProfileView.stories.jsx

I noticed the code of the `Profile` page component and the `ProfileView` could be improved upon. I've also expanded on its story, adding more possible scenarios. When I was working on that, I also noticed the styling was a bit off. I subsequently found out some things that could also be improved in `Rank` / `Cup`, which I did. See the screenshots below for comparison.
Additionally, I updated the routes a bit, removing the `exact` prop, which [doesn't exist anymore](https://stackoverflow.com/a/69866593/4496102) in `react-router` v6, and by removing the non-existent route for "session".

Style: Improve styling & stories of profile view, rank & cup

---

frontend/src/components/MatchingPairs/MatchingPairs.tsx

This PR sets a timestamp `start_of_turn` in the result of the first card.
First when the board has been loaded, then on every third click of a turn. 
Closes: #1298

Add timestamp for start of turn

---

backend/experiment/fixtures/experiment.json

Introduce a phase model and link it to existing blocks in the experiment.json fixtures.
Fixes #1357

Fixed: Add phase model and associate with blocks in experiment fixtures

---

backend/experiment/rules/categorization.py

Close #1333. Since I'm not quite sure whether the current change will break anything, can  either of you give this an extra look, @Evert-R and @albertas-jn ? I think you designed the original logic. The problems still arise from getting rid of the `first_round` method. NB: I did one playthrough up until the testing phase, and everything seemed to be working fine.

Bugfix: revise logic on start of categorization experiment

---

frontend/src/components/Histogram/Histogram.test.tsx
frontend/src/components/Histogram/Histogram.tsx
frontend/src/components/MatchingPairs/PlayCard.tsx
frontend/src/stories/Histogram.stories.jsx
frontend/src/stories/Histogram.stories.tsx

Re-added the random histogram bar changes as not to "help" the participant in the matching pairs experiment.
This PR adds the `random` prop (`false` by default) that makes the `Histogram` show random bar changes again. Additionally, the `interval` prop has been re-instated, which is used as the interval for random bar changes.
The `PlayCard` component then uses the `random` feature of the `Histogram` as it is used by the Matching Pairs game.
Fixes #1362

Fixed: Add `random` and `interval` props to `Histogram` component

---

backend/experiment/templates/edit-sections.html

Consistently set placeholders to "*" and refrain from calling methods directly in the Django template. Django does not allow you to call methods in templates. Originally, the placeholder attribute was only set to "*" when there was no song / artist name. I think it's better to just always set it. It will appear only whenever there is no value anyway.
Resolves #1327

Fixed: Refactor Django template to avoid method calls and set placeholders consistently

---

backend/experiment/static/experiment_form.js

Update the indicators for the toggle buttons in collapsible forms to use arrow symbols for better visual clarity.
Related to #1382

Refactor: refactor toggle button indicators for collapsible forms

---

backend/image/forms.py

Add help texts to the `ImageAdminForm` for improved user guidance during image uploads and management.
Resolves #1369

Docs: Enhance ImageAdminForm with additional fields and help texts

---

backend/experiment/serializers.py
backend/experiment/tests/test_views.py
backend/experiment/views.py

Close #1371: the bug was caused by an old session cookie, in which the active participant already had finished sessions. Going in from this branch will assume the participant hasn't played the experiments yet, and set `times_played` to 0. This means that after the `for` loop, `serialize_phase` would still return `None`. A bit of an edge case, but it's not unrealistic to assume that it would affect participants of active experiments after release.
This branch checks the minimum session count and then sets `times_played` accordingly. It also reintroduces the previous implementation with recursion: this means that the participant can resume a later phase, instead of just the first one.

Fix serialization error for returning participants

---

frontend/src/components/ListenCircle/ListenCircle.tsx

Enable random bars in the Histogram component during audio playback to visualize animation. This change is temporary and will be revisited for a more permanent solution.
Related to #1379

Fixed: Temporarily enable random bars in Histogram for audio playback animation

---

backend/experiment/migrations/0061_migrate_slugs_to_unique_temp_field.py

This PR adds a catch for experiments with duplicate slugs already in the database when migrating the slug to a unique field.

catch for duplictate slugs already in database

---

backend/docs/11_Exporting_result_data.md
backend/experiment/admin.py
backend/experiment/tests/test_admin_experiment.py

This PR adds the Block's `Feedback`  to the JSON export in the admin interface.

Add feedback to block json export

---

frontend/src/components/Preload/Preload.tsx
frontend/src/util/webAudio.ts

This PR fixes the bug that occurs when you play `matching_pairs_lite` for the second time (via the dashboard) with 8 originals.
When the sections are loaded the buffer list gets cleared before loading the first section.
we used `previousSource`  to determine wether a section had already been loaded. 
A section might still be loaded, but if it isn't added to the `buffers` object, it will not be passed on to matching pairs.
I now changed this it to checking the `buffers` object to check if a section has been loaded. 
Fixes: #1368

Use buffers object to check wether a section has already been loaded

---

backend/experiment/admin.py
backend/experiment/models.py
backend/experiment/static/experiment_dashboard.js
backend/experiment/static/experiment_dashboard_feedback.js
backend/experiment/static/experiment_dashboard_sessions.js
backend/experiment/templates/experiment-dashboard-feedback.html
backend/experiment/templates/experiment-dashboard-participants.html
backend/experiment/templates/experiment-dashboard-sessions.html
backend/experiment/templates/experiment-dashboard.html

This PR moves the feedback from the Block admin, where it could be edited, to the Experimenter dashboard, where it's read only.
closes: #1381

Move feedback to experimenter dashboard

---

backend/experiment/static/experiment_form.js

Implement a reinitialization function for django-select2 to ensure it handles new inlines correctly. This addresses the issue of select2 widgets not being instantiated on newly added forms.
Resolves #1408

Fixed(django-select2): Add reinitialization for django-select2 on form change

---

backend/experiment/rules/base.py
backend/experiment/rules/tests/test_base.py

Adjust the play again URL to ensure it includes the '/block' prefix for proper routing.
Resolves #1389 although we might want to discuss desired behavior in the nearby future

Fixed(redirect): Update play again URL format to include '/block' prefix

---

frontend/package.json
frontend/src/API.ts
frontend/src/components/AppBar/AppBar.test.tsx
frontend/src/components/Block/Block.test.tsx
frontend/src/components/Block/Block.tsx
frontend/src/components/Experiment/Header/Header.tsx
frontend/src/components/Explainer/Explainer.tsx
frontend/src/components/Final/Final.tsx
frontend/src/components/Histogram/Histogram.test.tsx
frontend/src/components/Histogram/Histogram.tsx
frontend/src/components/Info/Info.tsx
frontend/src/components/ListenCircle/ListenCircle.tsx
frontend/src/components/MatchingPairs/MatchingPairs.test.tsx
frontend/src/components/Playlist/Playlist.tsx
frontend/src/components/Score/Score.tsx
frontend/src/components/Trial/Trial.test.tsx
frontend/src/components/Trial/Trial.tsx
frontend/src/stories/Histogram.stories.tsx
frontend/src/stories/Playback.stories.tsx
frontend/src/types/Action.ts
frontend/src/types/Round.ts
frontend/src/util/stores.ts
frontend/src/util/webAudio.ts
frontend/vitest.config.ts

Introduce a new `RoundResponse` type for round management in the Block component, streamline the Action type definition, and enhance the Histogram component with improved randomization logic. Fix various type annotations and update tests to ensure proper functionality.
- It commits the `next_round` data to the `RoundSlice` in the zustand store every time a new round is received from a `next_round` http request.
- It also types the array of actions in `next_round` as "`Round`', which is basically an array of `Action`.
- It also keeps track of the "current action" by setting the index of the current action of the current round in the store.
- This store management of next round & action is currently done in parallel to the way the current round & action(s) are managed in the `Block` …

Refactor: Integrate Round management and enhance Histogram component

---

backend/experiment/admin.py
backend/experiment/forms.py
backend/experiment/static/collapsible_blocks.css
backend/experiment/static/collapsible_blocks.js
backend/experiment/static/experiment_form.css

Introduce collapsible functionality to block forms, enhancing user experience with improved visibility and layout. Update styles and documentation to support the new features.
Resolves #1380

Added: Add collapsible functionality to block forms with expand/collapse all buttons

---

.gitignore
backend/experiment/actions/redirect.py

Include a docstring for the Redirect action class to clarify its purpose and usage. Also, add `docs-pages-build` to .gitignore to prevent a locally generated mkdocs site to clutter your changes in git.

Docs: Add documentation for Redirect action and update .gitignore

---

backend/mkdocs.yml

Revise navigation headings in `mkdocs.yml` as discussed in the MUSCLE meeting. We could potentially use other headings of course, see also my notes:
```
- Documentation: 
- Do docs for *all* code in the Python code documentation (rename it to "Technical documentation" or "Low-level code documentation?) section but also do a higher level 
- Rename Frontend tools to "Preview frontend widgets"
- Rename MUSCLE to Getting Started / Introduction / User Guide
```

Docs: Update navigation headings in documentation

---

backend/experiment/actions/explainer.py

Enhance the documentation and type annotations for the `Explainer` action, improving clarity and type safety. This includes defining response types and refining the constructor and action methods.

Docs: Improve documentation and typing for `Explainer` action in backend

---

backend/experiment/actions/consent.py
backend/experiment/actions/final.py
backend/experiment/actions/utils.py
backend/experiment/serializers.py
scripts/mkdocs

Update the client component reference from `Consent.js` to `Consent.tsx`, introduce a MkDocs build script, and refactor social media serialization with a new `SocialMediaConfigDto` TypedDict. Clean up unused imports and enhance documentation with added docstrings.
I might have gone overboard a bit with the amount of documentation, so feel free to tell me where to cut down on. I do like the newly introduced Dto typing classes though, although I can imagine them to be in a separate file or something, just like we do in the frontend in the types directory. Lmk what you think. :-)

Docs: Update client references, add MkDocs build, and refactor social media serialization

---

backend/experiment/templates/edit-sections.html
backend/section/admin.py
backend/section/models.py

This PR:
- Adds a check to `_update_sections` and `edit_sections` that prevents users from entering a greater duration for an audio file than the actual duration.
- Refactors the `_update_sections` function:
When the `csv.DictReader` would find an error in a row it would return with an error message, but would only jump out of the `for` loop not out of the function, so that the sections it had already processed were still created, while the rest ignored. 
Now all the errors are first gathered and then shown in a list when returned to the admin
Row length errors as well as rows with invalid numbers will be shown in the admin, but will not be processed. 
Exceeding song duration errors will be shown in the admin but the setting will be corrected and saved.
While running tests the duration …

Fix er/song duration configuration

---

backend/experiment/actions/score.py

Improve type annotations and documentation for the `Score` action. This includes defining a `ScoreConfig` type and updating argument types in the `Score` class.

Docs: Enhance type annotations and documentation for Score action

---

backend/aml/base_settings.py

Configure the session cookie age to enhance security and user experience.
Resolves #1424

Config: Set session cookie age to 3 months

---

backend/experiment/actions/consent.py
backend/mkdocs.yml

**NB:** [Add pymdownx extensions](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks) for improved markdown rendering with syntax highlighting. See also screenshot below for a before & after:
**Before**
**After**

Docs: Enhance documentation and markdown support for Consent class

---

backend/experiment/actions/trial.py

Improve type annotations and documentation for the Trial action configuration. Add example usage to the documentation for better clarity and guidance.

Docs(Trial): Enhance Trial action configuration with type annotations and examples

---

backend/experiment/models.py
backend/experiment/tests/test_model.py

Address an issue preventing the deletion of blocks due to a block without a primary key being unable to relate to translated content.
Fixes #1436

Fixed: Fix deletion of blocks related to translated content

---

docker-compose.yaml

Pin postgres version to 14. 
`docker-compose-deploy` is still pinned to 16, as the servers' installations are quite recent. 
closes: #1459

Pin postgres version to 14 for older installations

---

backend/experiment/actions/wrappers.py

Enhance clarity and usability of the `two_alternative_forced` and `song_sync` functions by adding detailed type annotations and comprehensive docstrings. 

Docs: Improve type annotations and documentation for functions in `wrappers.py`

---

backend/experiment/actions/styles.py
frontend/src/stories/Trial.stories.jsx

Add docstrings for style constants in `styles.py` for better clarity. These don't seem to show up in mkdocs though... Maybe because they aren't classes/functions?
Fix the initial display issue of the Trial story to improve user experience by ensuring it shows correctly without requiring a click.

Docs: Improve documentation and enhance Trial story UX

---

backend/experiment/actions/final.py
backend/experiment/actions/tests/test_actions_final.py
backend/experiment/rules/matching_pairs_2025.py
frontend/src/components/Final/Final.test.tsx
frontend/src/components/Final/Final.tsx
frontend/src/types/Action.ts

Introduce a new option to display the participant's percentile rank in the Final action and component, along with enhanced tests to verify this functionality.
Fixes #1488

Fixed: Add `show_percentile` option to `Final` action & component

---

README.md

Include a link to the releases page in the documentation.
Resolves #1005

Docs: Add link to releases page for updates and changes

---

backend/experiment/management/commands/bootstrap.py

Change the experiment slug from "test" to "gold-msi" in the bootstrap command to reflect the current experiment configuration so that http://localhost:3000/gold-msi will match the bootstrapped experiment.

Fixed: Update default experiment slug in bootstrap command to `gold-msi`

---

backend/section/models.py

Close #1521, #1527. This does mean we cannot auto-compile durations of files anymore when adding files through the csv field. Should achieve playlist compilation through a management command instead.

Do not set duration when adding sections through csv

---

frontend/src/components/MatchingPairs/MatchingPairs.tsx

close #1524: instead of applying the `seen` attribute only during / after showing the score, apply it even before sending results to the backend.

apply `seen` condition to sections earlier

---

backend/experiment/rules/matching_pairs_2025.py

Close #1538. @bacor, can you check whether the information now returned by the `Final` action would be what you need to compile the Scoreboard? The text that's now returned is not (yet) rank dependent. Will tackle that one together with moving other texts to the backend.

fix: change order of questions and explainer

---

backend/experiment/rules/base.py
backend/experiment/rules/hooked.py
backend/experiment/rules/huang_2022.py
backend/experiment/rules/toontjehoger_1_mozart.py

This PR fixes an error reported by Sentry. This originally occurred in `hooked.py`, but I also found and fixed other rules files which might suffer from this bug.

bugfix: TypeError when result.score is `None`

---

backend/experiment/rules/duration_discrimination.py
backend/experiment/rules/tests/test_duration_discrimination.py

Sentry flagged errors coming from the Duration Discrimination experiments: the object returned from the rules' `next_round` was `None`. The problem was that instead of returning a `Final` action, the `staircasing_blocks` function returned `None`. This is of course incorrect - probably an error caused by refactoring.

fix: finalize experiment when max number of turnpoints is reached
