Amsterdam-Music-Lab/MUSCLE

backend/experiment/rules/thats_my_song.py
=> remove consent

frontend/src/components/FeedbackForm/FeedbackForm.js, frontend/src/components/Question/_ButtonArray.js
The onclick and keypress events attached to a label will submit twice.
In this PR I attached these events to the input of the buttonArray. 
resolves #589
=> Move click event to input (label double submits)

backend/experiment/templates/add-sections.html, backend/section/forms.py
This PR will filter the browsed files and validates the extention of the selected files. 
When the file extentions are invalid the input is cleared and the help text will be highlighted.
resolves #590
=> Feature er/section upload fixes

backend/experiment/rules/musical_preferences.py
At some point, we reversed the order of icons in the Music Preferences experiment, but then didn't adjust the scoring. So now, a well-liked song gets a low score, and a disliked song a high score. If we had already implemented #425 , I would change the scoring rule so it's more intuitive (higher is more popular), and then rescore existing results in the database based on that. For now, since we already have sessions with the current (lower is more popular) scoring scheme in the database, the faster fix is to present feedback to participants (which songs did they like most? And which songs did other people like most?) based on the "lower is better" scheme.
=> Music Preferences: reverse order of scores (lower is better)

README.md
=> Docs: Add troubleshooting section to README

frontend/package.json, frontend/src/components/Final/Final.js, frontend/src/components/Final/Final.test.js, frontend/yarn.lock
This pull request fixes a bug in the Final component where the finalizeSession function was not being called correctly. The bug caused the finalizeSession function to not be called when the Final component mounted. This pull request adds the missing call to finalizeSession in the useEffect hook.
Resolves #676
=> Fixed: finalizeSession bug in Final component

backend/.flake8, backend/experiment/actions/score.py, backend/experiment/questions/utils.py, backend/experiment/rules/tests/test_hooked.py, backend/experiment/rules/toontjehoger_1_mozart.py, backend/experiment/rules/toontjehoger_3_plink.py, backend/experiment/rules/toontjehoger_6_relative.py, backend/participant/tests.py, backend/result/tests/test_views.py, tests/tests-selenium.py
This pull request enables the E711 flake8 rule and fixes linting issues in the codebase.
=> Fixed: Enable E711 flake8 rule and fix linting issues

backend/.flake8, backend/experiment/models.py, backend/experiment/rules/duration_discrimination.py, backend/experiment/rules/rhythm_discrimination.py, backend/experiment/rules/toontjehoger_home.py, backend/participant/views.py
This pull request enables the E713 and E266 flake8 rules and fixes the corresponding issues.
=> Fix (Lint): Enable E713 & E266 flake8 rules and fix issues

.github/ISSUE_TEMPLATE/bug_report.md
See also: https://github.com/stevemao/github-issue-templates/blob/master/.github/ISSUE_TEMPLATE/BUG-REPORT.yml
I thought it looked pretty nice!
=> Config: Configure issue template with form

backend/experiment/actions/playback.py, backend/experiment/rules/matching_pairs.py, frontend/src/components/Histogram/Histogram.scss, frontend/src/components/Playback/MatchingPairs.js, frontend/src/components/Playback/MatchingPairs.scss, frontend/src/components/Playback/MatchingPairs.test.js, frontend/src/components/Playback/Playback.js, frontend/src/components/Trial/Trial.js, frontend/src/stories/MatchingPairs.stories.js
This pull request adds the functionality to display score feedback in the MatchingPairsGame component. It includes the following changes:
- Added a new prop called scoreFeedbackDisplay to the MatchingPairs component.
- Refactored the MatchingPairs component to support the scoreFeedbackDisplay prop.
- Added a new option called SCORE_FEEDBACK_DISPLAY to the MatchingPairs component.
- Updated the WithSmallBottomRightScoreFeedback story to demonstrate the new score feedback display option.
Resolves #716
=> Added: Add score feedback display options to MatchingPairsGame

frontend/src/components/Playback/Playback.js, frontend/src/util/audioControl.js, frontend/src/util/webAudio.js
This PR checks for the user's ios version and switches to 'EXTERNAL' if the version < 17.
It also fixes a bug that only one sound got played in 'EXTERNAL' mode in matching pairs.
=> Bugfix er/iosversion fix

frontend/src/components/Playback/MatchingPairs.js, frontend/src/components/Playback/MatchingPairs.scss, frontend/src/components/VisualMatchingPairs/VisualMatchingPairs.js, frontend/src/stories/VisualMatchingPairs.stories.js
Resolves #756
@hhoning @Lia-JX-Li  This is what it should look like, right?
=> Fixed: Correctly display top feedback & score in (Visual)MatchingPairs

frontend/DockerfileLegacy, frontend/src/components/App/App.js
This PR updates the `develop` branch with the latest commits from `main` (release `v1.9.1` and `v1.9.2`) and the `DockerLegacy` file.
=> Release v1.9.2 (main -> develop)

frontend/src/components/App/App.js
This pull request refactors the query parameter handling in the App.js file. It fixes an issue where the queryParams variable was being redeclared and not used correctly. The fix ensures that the participantQueryParams variable is used instead.
=> Fixed: Refactor query parameter handling in App.js

frontend/src/components/MatchingPairs/PlayCard.js, frontend/src/components/MatchingPairs/PlayCard.test.js
=> fix: do not apply animation class if `showAnimations=false`

backend/experiment/actions/tests/test_wrappers.py, backend/experiment/actions/utils.py, backend/experiment/actions/wrappers.py, backend/experiment/tests/test_actions.py
=> Save `continuation_correctness` to session json_data

backend/experiment/admin.py, backend/experiment/forms.py
This pull request fixes a duplicate import in the code that caused [this issue](https://github.com/Amsterdam-Music-Lab/MUSCLE/pull/886#issuecomment-2019895386) caused by #886 and additionally removes unused imports.
=> Fixed: Fix duplicate import and remove unused imports

frontend/src/components/Experiment/Experiment.jsx, frontend/src/components/Experiment/Experiment.test.jsx
Close #953 (see for the technical description of the problem), and in consequence, close #937 and close #938.
=> Fix session mixup (#953)

package.json
=> Chore: Update app name to muscle

frontend/src/components/ExperimentCollection/ExperimentCollectionDashboard/ExperimentCollectionDashboard.tsx
Close #941 : remove the header altogether for now, with a structural solution coming up with #989.
=> quick and diry fix: remove header

frontend/vite.config.ts
I'm planning to enable the source maps to ease debugging in the browser.
=> Added: Enable sourcemap generation in build configuration

.github/workflows/podman.yml, .gitignore, e2e/Dockerfile, e2e/run-tests, e2e/tests-selenium.ini, e2e/tests-selenium.py
This pull request adds a Dockerfile and test scripts for running Selenium tests in a Docker container. The Dockerfile installs the necessary dependencies, such as the Selenium Python package, Chromium browser, and Chrome WebDriver. The test scripts allow for running the tests either in a container or in an interactive bash terminal.
Related to #746
=> CI: Configure Selenium E2E tests to run in Docker and in Podman workflow

backend/experiment/rules/base.py, backend/experiment/rules/hooked.py, backend/experiment/rules/matching_pairs.py, backend/experiment/rules/tests/test_base.py, backend/experiment/rules/thats_my_song.py, backend/experiment/rules/visual_matching_pairs.py, backend/experiment/tests/test_views.py, frontend/src/components/Experiment/Experiment.jsx, frontend/src/components/Final/Final.jsx, frontend/src/components/Final/Final.test.jsx, frontend/src/components/Final/FinalButton.tsx, frontend/src/stories/Final.stories.jsx, package.json
Merge this branch back into `develop` after the hot fix from #1046 / #1051
=> Fixed: Fix play again URL rendering

backend/experiment/actions/playback.py, backend/experiment/rules/toontjehoger_4_absolute.py, backend/experiment/rules/toontjehoger_5_tempo.py, backend/experiment/rules/toontjehogerkids_4_absolute.py, backend/experiment/rules/toontjehogerkids_5_tempo.py, frontend/src/components/ExperimentCollection/ExperimentCollectionDashboard/ExperimentCollectionDashboard.tsx, frontend/src/components/Footer/Footer.test.tsx, frontend/src/components/Header/Header.tsx, frontend/src/components/Page/DefaultPage.test.jsx, frontend/src/components/Playback/MultiPlayer.jsx, frontend/src/components/Playback/Multiplayer.scss, frontend/src/components/Playback/Playback.jsx, frontend/src/stories/Trial.stories.jsx
This pull request adds the "neutral-inverted" style to the play buttons in the codebase. It also updates the necessary components and files to use this new style.
Resolves #1057
=> Added: Style play buttons according to neutral-inverted style

backend/experiment/rules/toontjehoger_2_preverbal.py
Close https://github.com/Amsterdam-Music-Lab/MUSCLE/issues/1072, with a cleaned up commit history.
=> feat: validate Preverbal playlist

backend/experiment/rules/toontjehoger_6_relative.py
=> TH 6 playlist validation

backend/experiment/rules/toontjehoger_3_plink.py
=> TH3: add Plink validation

backend/experiment/rules/tests/test_toontjehoger_5_tempo.py, backend/experiment/rules/tests/test_toontjehoger_kids_5_tempo.py, backend/experiment/rules/toontjehoger_5_tempo.py, backend/experiment/rules/toontjehogerkids_5_tempo.py
This pull request adds tag validation to the ToontjeHoger(Kids)5Tempo rules. The `validate_tags` method has been implemented to check if the tags in the playlist are valid. Additionally, a test case has been added to ensure that the `validate_playlist` method does not raise any errors for invalid tags.
Resolves #1076
=> TH5 Playlist Validation: Add playlist tag validation to ToontjeHoger(Kids)5Tempo rules

frontend/src/components/ExperimentCollection/ExperimentCollection.scss, frontend/src/components/Footer/Footer.scss
=> Fixed: update max-width in Footer.scss to 1200px

frontend/src/components/ExperimentCollection/ExperimentCollection.scss
=> Fixed(Styling): Improve spacing between experiment collection intro & score

backend/aml/base_settings.py
=> Fixed: Turn off markdown safe mode to allow iframes in markdown

backend/experiment/models.py
```GroupedExperiment``` still had a reference to group, Changed to phase
=> change group to phase

frontend/src/components/Circle/Circle.test.tsx, frontend/src/components/Circle/Circle.tsx
This pull request refactors the Circle component to TypeScript and updates the tests accordingly.
=> Refactor: Refactor Circle component to TypeScript and update tests

backend/aml/base_settings.py, backend/experiment/admin.py, backend/requirements.in/base.txt, backend/requirements/dev.txt, backend/requirements/prod.txt
It will look like this:
Resolves #1192
=> Added: Add Experiment->Phase->Block nested inline forms

backend/experiment/admin.py, backend/image/admin.py, backend/image/tests/test_admin.py, backend/section/admin.py, backend/theme/admin.py
I ran [Vulture](https://github.com/jendrikseipp/vulture) and [Bandit](https://github.com/PyCQA/bandit) on the backend project and found some security / linting issues which I fix here.
=> Chore: Improve security & fix some linting errors

backend/experiment/admin.py, backend/experiment/templates/csv-export.html
Changed the term experiment to block in csv export screen
=> Changed experiment to block

backend/DockerfileDevelop, backend/aml/development_settings.py, backend/requirements.in/dev.txt, backend/requirements/dev.txt, scripts/graph-model
This pull request adds the necessary dependencies to the development version of the MUSCLE project in order to generate ER diagrams of the database. The `DockerfileDevelop` is updated to install `graphviz` and `graphviz-dev`, and the `development_settings.py` file is modified to include `django_extensions` and configure `pygraphviz` for generating the diagrams.
A script has also been added to easily generate an new version of the visual representation of the database:
```sh
scripts/graph-model
```
=> Added: Install django-extensions & (py)graphviz for ER diagram generation

backend/DockerfileDevelop, backend/aml/development_settings.py, backend/aml/graphviz_settings.py, backend/requirements.in/dev.txt, backend/requirements/dev.txt, docker-compose.yaml, scripts/graph-model
- Updated `DockerfileDevelop` to include a new multi-stage build for generating database ER diagrams using Graphviz and Django extensions.
- Added `graphviz_settings.py` dedicated Django settings for ER diagram generation.
- Updated `development_settings.py` to include `debug_toolbar` and adjusted installed apps order.
- Modified `requirements.in/dev.txt` and `requirements/dev.txt` to remove `django-extensions` and `pygraphviz`, as they are now handled in the Docker image.
- Updated `docker-compose.yaml` to specify the `base` target for the development build.
- Enhanced the `graph-model` script to build and run the Docker container for generating the ER diagram.
Resolves #1230
=> Config: Add Docker configuration for generating database ER diagrams

backend/experiment/management/commands/templates/experiment.py, backend/experiment/rules/toontjehoger_2_preverbal.py
=> Remove occurrences of `section_from_any_song`

frontend/src/util/audioControl.ts
This pull request refactors the `audioControl.js` file to TypeScript. The changes include converting function parameters to typed variables and updating import statements to use TypeScript syntax.
=> Refactor audioControl.js to TypeScript

README.md
=> Fix(Docs): Fix paths to workflow status badges

.github/workflows/ci.yml, .github/workflows/podman.yml, README.md, docker-compose.yaml, scripts/build-front, scripts/lint-back, scripts/lint-front, scripts/manage, scripts/test-back, scripts/test-back-coverage, scripts/test-front, scripts/test-front-ci, scripts/test-front-watch
Update the Docker commands in the scripts to use the "docker compose" syntax instead of "docker-compose".
=> Fixed: Refactor Docker commands in scripts to use `docker compose`

frontend/src/components/Circle/Circle.scss, frontend/src/stories/AutoPlay.stories.tsx
=> Fixed: Fix Circle percentage overlap issue (attempt 3)

nginx/custom-nginx.conf
Resolves #1276
NB: This merges to `develop` so it could be merged already as it will only be released together with the great refactor.
=> Chore: Redirect /collection/{slug} to /{slug}

frontend/src/API.ts, frontend/src/components/Block/Block.tsx, frontend/src/components/Experiment/Experiment.tsx, frontend/src/hooks/useHeadDataFromExperiment.test.ts, frontend/src/hooks/useHeadDataFromExperiment.ts, frontend/src/util/stores.ts
=> Added: Set head data of Experiment page based on name, description and its theme's image

backend/experiment/rules/anisochrony.py, backend/experiment/rules/beat_alignment.py, backend/experiment/rules/duration_discrimination.py, backend/experiment/rules/h_bat.py, backend/experiment/rules/rhythm_discrimination.py
=> Add `validate_playlist` method for rhythm experiments

backend/experiment/rules/duration_discrimination.py, backend/experiment/rules/h_bat.py
=> Fix DDI/HBAT crash on end of block

backend/experiment/static/experiment_dashboard.js, backend/experiment/static/experiment_dashboard_sessions.js, backend/experiment/templates/experiment-dashboard-participants.html, backend/experiment/templates/experiment-dashboard-sessions.html, backend/experiment/templates/experiment-dashboard.html
Update the result iteration to use the `all()` method, addressing the "ActionNotCallable" error encountered in the Experimenter's Dashboard. Enhance the user interface by replacing session and participant containers with dialog elements, improving the display of results, and adding a count of results in the preview button.
Fixes #1345
=> Fix: ActionNotCallable error in Experimenter's Dashboard

frontend/src/components/ProgressBar/ProgressBar.scss, frontend/src/components/ProgressBar/ProgressBar.test.tsx, frontend/src/components/ProgressBar/ProgressBar.tsx, frontend/src/stories/ProgressBar.stories.tsx
Introduce a new ProgressBar component that allows customization of properties and styles. Enhance the associated stories with decorators for improved visualization.
The component is not yet configured to be used in the `AppBar` as it kind of depends on the technical approach we want to take with regards to the content. See also the related issue of #1334
=> Added: Add `ProgressBar` component

backend/aml/base_settings.py, backend/experiment/forms.py, backend/requirements.in/base.txt, backend/requirements/dev.txt, backend/requirements/prod.txt
Incorporate django-select2 to improve the user experience for selecting multiple items in forms. Update settings and requirements to include the new package.
Resolves #1383
=> Added: Integrate django-select2 for enhanced form field selection

frontend/.pnp.cjs, frontend/package.json, frontend/src/config/sentry.ts, frontend/yarn.lock
Fix Sentry issues by updating the library and by correctly configuring browser tracing.
=> Fixed(Sentry): Update Sentry and fix Sentry configuration for React V6

backend/experiment/rules/hooked.py, backend/session/models.py
=> Fix: Hooked does not display song name & artist in Score view

backend/experiment/rules/toontjehoger_3_plink.py
Replace the undefined `session.round_passed()` method with the correct `session.get_rounds_passed()` method and format the code in `toontjehoger_3_plink.py`.
=> Fixed(th3plink): Fix session method and format code

backend/experiment/static/collapsible_blocks.js
Address several issues affecting the functionality of the block form collapse feature, improving event handling and ensuring proper initialization of click handlers.
=> Fixed: Fix glitches in block form collapse feature

backend/experiment/actions/score.py, backend/experiment/actions/tests/test_actions_score.py, backend/experiment/rules/hooked.py, backend/experiment/rules/tests/test_hooked.py, backend/experiment/rules/toontjehogerkids_3_plink.py
=> Fixed: show correct song in Hooked experiments

.github/workflows/docs.yml
Upgrade GitHub Actions used for deploying pages to their latest versions to improve performance and security.
Resolves #1418
=> Update GitHub Actions for pages deployment

backend/experiment/actions/playback.py, backend/experiment/rules/__init__.py, backend/experiment/rules/matching_pairs.py, backend/experiment/rules/matching_pairs_2025.py, backend/experiment/rules/matching_pairs_icmpc.py, backend/experiment/rules/matching_pairs_lite.py, backend/experiment/rules/tests/test_matching_pairs.py, frontend/.pnp.cjs, frontend/.storybook/preview.js, frontend/package.json, frontend/public/mockServiceWorker.js, frontend/src/components/Button/Button.tsx, frontend/src/components/MatchingPairs/MatchingPairs.test.tsx, frontend/src/components/MatchingPairs/MatchingPairs.tsx, frontend/src/components/Overlay/Overlay.scss, frontend/src/components/Overlay/Overlay.test.tsx, frontend/src/components/Overlay/Overlay.tsx, frontend/src/components/Playback/Playback.tsx, frontend/src/stories/MatchingPairs.stories.tsx, frontend/src/stories/Overlay.stories.tsx, frontend/src/types/Playback.ts, frontend/yarn.lock
- Introduce a tutorial overlay for the MatchingPairs game, allowing users to receive guidance. 
- Refactor MatchingPairs to avoid prop mutation.
- Update the Button component to support multiple clicks when specified (so the tutorial overlay can be closed multiple times).
- Integrate MSW for API mocking in Storybook. 
- Add relevant tests for the new features.
Resolves #1338
=> Added: Enhance MatchingPairs game with tutorial overlay

backend/mkdocs.yml
This PR splits the documentation relevant for researchers from the technical documentation.
=> Add ruleset documentation heading

backend/experiment/actions/info.py
=> Docs: Enhance Info action documentation and refactor class definition

backend/experiment/actions/base_action.py
=> Docs: Improve documentation and type annotations for BaseAction class

backend/experiment/actions/frontend_style.py, backend/experiment/actions/redirect.py
Improve type annotations and documentation for frontend style classes.
=> Docs: Enhance documentation for the frontend style classes

docker-compose-deploy.yml, docker-compose.yaml
Update the PostgreSQL image in the docker-compose configuration to version 16 as version 17 (which is used without explicifying a version) is not compatible with a data directory created with version 16.
Fixes #1458
=> Fixed: Set PostgreSQL image to version 16 in docker-compose files

backend/experiment/actions/form.py
Enhance the documentation and typing for the `Form` action class and all `Question` classes.
=> Docs: Improve documentation and typing for `Form` and `Question` classes

backend/experiment/actions/utils.py
Enhance type annotations and documentation for clarity and usability of utility functions related to experiment actions.
=> Docs: Improve type annotations and documentation for utility functions in experiment actions

frontend/src/components/MatchingPairs/MatchingPairs.tsx
This PR fixes the bug that caused the timestamp to not always being logged.
Fixes: #1464
=> Fix logging of timestamps

backend/experiment/templates/edit-sections.html
Step increment setting was set on the wrong field
=> Move `step` to the right input 'start_time'

backend/experiment/actions/final.py, backend/experiment/actions/tests/test_actions_final.py, backend/experiment/actions/types.py, backend/experiment/rules/base.py, backend/experiment/rules/matching_pairs.py, backend/experiment/rules/matching_pairs_2025.py, frontend/src/components/Cup/Cup.scss, frontend/src/components/Final/Final.scss, frontend/src/components/Final/Final.test.tsx, frontend/src/components/Final/Final.tsx, frontend/src/scss/variables.scss, frontend/src/stories/Final.stories.jsx, frontend/src/types/Action.ts
Introduce the FinalV2 component, which includes additional feedback information, a rank bar section, and new styling elements. Update the color scheme with a new goldmp2 variable for improved visual representation.
Related to #1335
=> Added: Add FinalV2 component with enhanced feedback and ranking features

backend/image/models.py
Improve the documentation for the Image model and its fields, providing clearer descriptions and help texts.
Resolves #1469
=> Docs: Enhance Image model documentation and improve field help texts

frontend/.pnp.cjs, frontend/package.json, frontend/yarn.lock
Upgrade Storybook and its related dependencies to version 8.6 to ensure compatibility and access to the latest features.
=> Chore(deps): Upgrade Storybook to version 8.6

frontend/src/stories/Final.stories.jsx
Introduce a new story for FinalTextHtml that includes extensive HTML content to enhance testing capabilities.
=> Story(Final): Add FinalTextHtml story for comprehensive HTML testing

frontend/index.html
Merge `main` back into `develop` after the release of [v3.2.1](https://github.com/Amsterdam-Music-Lab/MUSCLE/releases/tag/v3.2.1) (excellent version number)
=> chore: add Plausible analytics script to index.html (#1510)

backend/experiment/actions/wrappers.py, backend/result/score.py, backend/result/tests/test_score.py
=> Adjust name of continuation->verification scoring rule

backend/experiment/rules/tests/test_hooked.py
The current branch adds a simulation (which can be run by commenting out the `@skip` decorator) of what should happen if a TeleTunes experiment is run, and sections are selected every round. Related to #1322 : the output of the simulation is uniformishly distributed, though, while the output from the app server had much more marked peaks and troughs.
=> feat: add simulation of Hooked section selection

backend/question/admin.py, backend/question/questions.py, backend/question/tests/test_admin.py, backend/question/tests/test_utils.py
As it would be very time consuming to create questions which basically have the same answer options from scratch, this branch adds the option to duplicate questions through the admin interface.
=> Duplicate question
